video:
  input_path:  "input/input_video.mp4"
  output_path: "outputs/tracked_output1.mp4"

model:
  weights: "yolov8m.pt"
  device:  "cuda:0"
  half:    true
  imgsz:   640

  person_class_id: 0
  ball_class_id:   32
  person_conf: 0.30
  iou: 0.60

tracker:
  config: "trackers/botsort_reid_stable.yaml"

smoothing:
  enable: true
  ema_alpha: 0.4

# BALL DETECTION OFF
ball_detection_enabled: false

# ID STABILIZER OFF - BoT-SORT ReID handles all ID matching
id_stabilizer_enabled: false

visual:
  person_thickness: 2
  font_scale: 0.7